/*
 * NNP-I Linux Driver
 * Copyright (c) 2017-2019, Intel Corporation.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 */

#include "ice_debug.h"
#include "cve_device.h"
#include "cve_driver.h"
#include "osmm_interface.h"
#include "device_interface.h"
#include "ice_mmu_inner_regs.h"
#include "sph_device_regs.h"
#include "idc_regs_regs.h"
#include "mmio_hub_regs.h"
#include "CVG_MMU_1_system_map_regs.h"
#include "mmio_semaphore_regs.h"
#include "ice_mmu_inner_regs.h"
#include "project_device_interface.h"

const char *get_cve_jobs_group_status_str(uint32_t status)
{
	switch (status) {

	case CVE_JOBSGROUPSTATUS_PENDING:
		return "JOBSGROUPSTATUS_PENDING";
	case CVE_JOBSGROUPSTATUS_DISPATCHED:
		return "JOBSGROUPSTATUS_DISPATCHED";
	case CVE_JOBSGROUPSTATUS_COMPLETED:
		return "JOBSGROUPSTATUS_COMPLETED";
	case CVE_JOBSGROUPSTATUS_ABORTED:
		return "JOBSGROUPSTATUS_ABORTED";
	default:
		return "Unknown";
	}
}

const char *get_osmm_memory_type_str(uint32_t type)
{
	switch (type) {

	case OSMM_KERNEL_MEMORY:
		return "KERNEL_MEMORY";
	case OSMM_USER_MEMORY:
		return "USER_MEMORY";
	case OSMM_SHARED_MEMORY:
		return "SHARED_MEMORY";
	default:
		return "Unknown";
	}
}

const char *get_cve_memory_protection_str(uint32_t prot)
{
	switch (prot) {

	case CVE_MM_PROT_READ:
		return "R";
	case CVE_MM_PROT_WRITE:
		return "W";
	case (CVE_MM_PROT_READ | CVE_MM_PROT_WRITE):
		return "RW";
	case CVE_MM_PROT_EXEC:
		return "X";
	case (CVE_MM_PROT_READ | CVE_MM_PROT_EXEC):
		return "RX";
	default:
		return "Unknown";
	}
}

const char *get_cve_surface_direction_str(uint32_t dir)
{
	switch (dir) {

	case CVE_SURFACE_DIRECTION_IN:
		return "IN";
	case CVE_SURFACE_DIRECTION_OUT:
		return "OUT";
	case CVE_SURFACE_DIRECTION_INOUT:
		return "INOUT";
	default:
		return "Unknown";
	}
}

const char *get_fw_binary_type_str(uint32_t type)
{
	switch (type) {

	case CVE_FW_TLC_TYPE:
		return "TLC";
	case CVE_FW_IVP_MFW_TYPE:
		return "IVP_MFW";
	case CVE_FW_ASIP_MFW_TYPE:
		return "ASIP_MFW";
	case CVE_FW_IVP_BANK0_TYPE:
		return "IVP_BANK0";
	case CVE_FW_IVP_BANK1_TYPE:
		return "IVP_BANK1";
	case CVE_FW_ASIP_BANK0_TYPE:
		return "ASIP_BANK0";
	case CVE_FW_ASIP_BANK1_TYPE:
		return "ASIP_BANK1";
	case CVE_FW_CB_TYPE_START:
		return "EMB_CB";
	default:
		return "Unknown";
	}
}

const char *get_idc_regs_str(uint32_t offset)
{
	switch (offset) {
	case IDC_REGS_IDC_MMIO_BAR0_MEM_IDCSPARE_MMOFFSET:
		return "IDC_ICE_DBG_INDICATION_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_IDCINTST_MMOFFSET:
		return "IDC_INTR_STATUS_LOW_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_IDCINTST_MMOFFSET + 4:
		return "IDC_INTR_STATUS_HIGH_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEINTST_MMOFFSET:
		return "ICE_INTR_STATUS_LOW_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEINTST_MMOFFSET + 4:
		return "ICE_INTR_STATUS_HIGH_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEPOOL0_MMOFFSET:
		return "ICEPOOL0_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEPOOL1_MMOFFSET:
		return "ICEPOOL1_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEPOOL2_MMOFFSET:
		return "ICEPOOL2_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEPOOL3_MMOFFSET:
		return "ICEPOOL3_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEPOOL4_MMOFFSET:
		return "ICEPOOL4_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEPOOL5_MMOFFSET:
		return "ICEPOOL5_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICENOTA0_MMOFFSET:
		return "NOTFICATION_ADDR0_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICENOTA1_MMOFFSET:
		return "NOTFICATION_ADDR1_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICENOTA2_MMOFFSET:
		return "NOTFICATION_ADDR2_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICENOTA3_MMOFFSET:
		return "NOTFICATION_ADDR3_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT0_MMOFFSET:
		return "CNTR_0_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT1_MMOFFSET:
		return "CNTR_1_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT2_MMOFFSET:
		return "CNTR_2_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT3_MMOFFSET:
		return "CNTR_3_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT4_MMOFFSET:
		return "CNTR_4_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT5_MMOFFSET:
		return "CNTR_5_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT6_MMOFFSET:
		return "CNTR_6_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT7_MMOFFSET:
		return "CNTR_7_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT8_MMOFFSET:
		return "CNTR_8_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT9_MMOFFSET:
		return "CNTR_9_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT10_MMOFFSET:
		return "CNTR_10_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT11_MMOFFSET:
		return "CNTR_11_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT12_MMOFFSET:
		return "CNTR_12_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT13_MMOFFSET:
		return "CNTR_13_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT14_MMOFFSET:
		return "CNTR_14_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT15_MMOFFSET:
		return "CNTR_15_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT16_MMOFFSET:
		return "CNTR_16_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT17_MMOFFSET:
		return "CNTR_17_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT18_MMOFFSET:
		return "CNTR_18_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT19_MMOFFSET:
		return "CNTR_19_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT20_MMOFFSET:
		return "CNTR_20_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT21_MMOFFSET:
		return "CNTR_21_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT22_MMOFFSET:
		return "CNTR_22_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT23_MMOFFSET:
		return "CNTR_23_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT24_MMOFFSET:
		return "CNTR_24_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT25_MMOFFSET:
		return "CNTR_25_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT26_MMOFFSET:
		return "CNTR_26_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT27_MMOFFSET:
		return "CNTR_27_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT28_MMOFFSET:
		return "CNTR_28_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT29_MMOFFSET:
		return "CNTR_29_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT30_MMOFFSET:
		return "CNTR_30_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_EVCTPROT31_MMOFFSET:
		return "CNTR_31_ACCESS_CONTROL_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICERST_MMOFFSET:
		return "ICE_RESET_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICERDY_MMOFFSET:
		return "ICE_READY_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICENOTE_MMOFFSET:
		return "ICE_NOTIFY_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEINTEN_MMOFFSET:
		return "ICE_INTR_ENABLE_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEINTEN_MMOFFSET + 4:
		return "ICE_ERR_INTR_ENABLE_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_IDCINTEN_MMOFFSET:
		return "IDC_INTR_ENABLE_LOW_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_IDCINTEN_MMOFFSET + 4:
		return "IDC_INTR_ENABLE_HIGH_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEPE_MMOFFSET:
		return "ICE_POWER_ENABLE_REG";
	case IDC_REGS_IDC_MMIO_BAR0_MEM_ICEMASKSTS_MMOFFSET:
		return "ICE_MASK_REG";
	default:
		return "Unknown";
	}
}
#ifdef ENABLE_SPH_STEP_B
const char *get_other_regs_str(uint32_t offset)
{
	switch (offset) {
	default:
		return "Unknown";
	}
}
#else
const char *get_other_regs_str(uint32_t offset)
{
	switch (offset) {
	case CVE_MMIO_HUB_HW_REVISION_MMOFFSET:
		return "HW_REVISION_REG";
	default:
		return "Unknown";
	}
}
#endif
const char *get_regs_str(uint32_t offset)
{
	switch (offset) {
	case ICE_MMU_BASE + ICE_MMU_AXI_TABLE_PT_INDEX_BITS_MMOFFSET:
		return "AXI_TABLE_PT_INDEX_REG";
	case ICE_MMU_BASE + ICE_MMU_TLC_AXI_ATTRIBUTES_MMOFFSET:
		return "TLC_AXI_ATTRIBUTES_REG";
	case ICE_MMU_BASE + ICE_MMU_ASIP_AXI_ATTRIBUTES_MMOFFSET:
		return "ASIP_AXI_ATTRIBUTES_REG";
	case ICE_MMU_BASE + ICE_MMU_DSP_AXI_ATTRIBUTES_MMOFFSET:
		return "DSP_AXI_ATTRIBUTES_REG";
	case ICE_MMU_BASE + ICE_MMU_PAGE_WALK_AXI_ATTRIBUTES_MMOFFSET:
		return "PAGE_WALK_AXI_ATTRIBUTES_REG";
	case CVE_MMIO_HUB_DTF_CONTROL_MMOFFSET:
		return "DTF_CONTROL_REG";
	case CVE_MMIO_HUB_PRE_IDLE_DELAY_COUNT_MMOFFSET:
		return "PRE_IDLE_DELAY_COUNT_REG";
	case CVE_MMIO_HUB_CVE_CONFIG_MMOFFSET:
		return "ICE_CONFIG_REG";
	case CVE_MMIO_HUB_PROG_CORES_CONTROL_MMOFFSET:
		return "PROG_CORES_CONTROL_REG";
#ifdef _DEBUG
	case ICE_DEBUG_CFG_REG:
		return "ICE_DEBUG_CFG_REG";
#endif
	case CVE_MMIO_HUB_NEW_COMMAND_BUFFER_DOOR_BELL_MMOFFSET:
		return "CB_DOORBELL_REG";
	case CVE_MMIO_HUB_INTERRUPT_MASK_MMOFFSET:
		return "INTERRUPT_MASK_REG";
	case CVE_MMIO_HUB_TLC_WR_PULSE_MMOFFSET:
		return "TLC_WR_PULSE_REG";
	case CVE_MMIO_HUB_INTERRUPT_STATUS_MMOFFSET:
		return "INTERRUPT_STATUS_REG";
	case ICE_MMU_ATU0_BASE + CVG_MMU_1_SYSTEM_MAP_MEM_INVALIDATE_OFFSET:
		return "MMU_ATU0_MEM_INVALIDATE_REG";
	case ICE_MMU_ATU1_BASE + CVG_MMU_1_SYSTEM_MAP_MEM_INVALIDATE_OFFSET:
		return "MMU_ATU1_MEM_INVALIDATE_REG";
	case ICE_MMU_ATU2_BASE + CVG_MMU_1_SYSTEM_MAP_MEM_INVALIDATE_OFFSET:
		return "MMU_ATU2_MEM_INVALIDATE_REG";
	case ICE_MMU_ATU3_BASE + CVG_MMU_1_SYSTEM_MAP_MEM_INVALIDATE_OFFSET:
		return "MMU_ATU3_MEM_INVALIDATE_REG";
	case ICE_MMU_ATU0_BASE +
CVG_MMU_1_SYSTEM_MAP_MEM_PAGE_TABLE_BASE_ADDRESS_OFFSET:
		return "MMU_ATU0_PT_BASE_ADDR_REG";
	case ICE_MMU_ATU1_BASE +
CVG_MMU_1_SYSTEM_MAP_MEM_PAGE_TABLE_BASE_ADDRESS_OFFSET:
		return "MMU_ATU1_PT_BASE_ADDR_REG";
	case ICE_MMU_ATU2_BASE +
CVG_MMU_1_SYSTEM_MAP_MEM_PAGE_TABLE_BASE_ADDRESS_OFFSET:
		return "MMU_ATU2_PT_BASE_ADDR_REG";
	case ICE_MMU_ATU3_BASE +
CVG_MMU_1_SYSTEM_MAP_MEM_PAGE_TABLE_BASE_ADDRESS_OFFSET:
		return "MMU_ATU3_PT_BASE_ADDR_REG";
	case CVE_TLC_HI_BASE + CVE_TLC_HI_TLC_DUMP_BUFFER_CONFIG_REG_MMOFFSET:
		return "TLC_DUMP_CONFIG_REG";
	case CVE_TLC_HI_BASE + CVE_TLC_HI_TLC_DUMP_CONTROL_REG_MMOFFSET:
		return "TLC_DUMP_CONTROL_REG";
	case CVE_MMIO_HUB_COMMAND_BUFFER_DESCRIPTORS_BASE_ADDRESS_MMOFFSET:
		return "CB_DESC_BASE_ADDR_REG";
	case CVE_MMIO_HUB_COMMAND_BUFFER_DESCRIPTORS_ENTRIES_NR_MMOFFSET:
		return "CB_DESC_ENTRIES_NR_REG";
	case ICE_MMU_BASE + ICE_MMU_MMU_CONFIG_MMOFFSET:
		return "MMU_CONFIG_REG";
	case CVE_MMIO_HUB_CVE_WATCHDOG_INIT_MMOFFSET:
		return "ICE_WATCHDOG_INIT_REG";
	case ICE_MMU_BASE + ICE_MMU_MMU_FAULT_DETAILS_MMOFFSET:
		return "MMU_FAULT_DETAILS_REG";
	case ICE_MMU_BASE + ICE_MMU_FAULT_LINEAR_ADDRESS_MMOFFSET:
		return "MMU_FAULT_LINEAR_ADDR_REG";
	case ICE_MMU_BASE + ICE_MMU_FAULT_PHYSICAL_ADDRESS_MMOFFSET:
		return "MMU_FAULT_PHYSICAL_ADDR_REG";
	case ICE_MMU_BASE + ICE_MMU_MMU_CHICKEN_BITS_MMOFFSET:
		return "MMU_CHICKEN_BITS_REG";
	case CVE_MMIO_HUB_CBB_ERROR_CODE_MMOFFSET:
		return "CBB_ERROR_CODE_REG";
	case CVE_MMIO_HUB_CBB_ERROR_INFO_MMOFFSET:
		return "CBB_ERROR_INFO_REG";
	case CVE_MMIO_HUB_TLC_INFO_MMOFFSET:
		return "TLC_INFO_REG";
	case CVE_MMIO_HUB_GENERAL_PURPOSE_REGS_MMOFFSET ...
		(CVE_MMIO_HUB_GENERAL_PURPOSE_REGS_MMOFFSET + (4 * 15)):
		return "GENERAL_PURPOSE_REG";
	case ICE_MMU_BASE + ICE_MMU_PAGE_SIZES_MMOFFSET ...
		(ICE_MMU_BASE + ICE_MMU_PAGE_SIZES_MMOFFSET + (4 * 127)):
		return "PAGE_SIZE_CONFIG_REG";
	case CVE_SEMAPHORE_BASE +
CVE_SEMAPHORE_MMIO_CVE_REGISTER_DEMON_ENABLE_MMOFFSET:
		return "SEMAPHORE_DEMON_ENABLE_REG";
	case CVE_SEMAPHORE_BASE +
CVE_SEMAPHORE_MMIO_CVE_REGISTER_DEMON_CONTROL_MMOFFSET:
		return "SEMAPHORE_DEMON_CONTROL_REG";
	case CVE_SEMAPHORE_BASE +
		CVE_SEMAPHORE_MMIO_CVE_REGISTER_DEMON_TABLE_MMOFFSET ...
		   (CVE_SEMAPHORE_BASE +
		      CVE_SEMAPHORE_MMIO_CVE_REGISTER_DEMON_TABLE_MMOFFSET +
			(4 * 31)):
		return "SEMAPHORE_DEMON_TABLE_REG";
	case CVE_MMIO_HUB_ECC_SERRCOUNT_MMOFFSET:
		return "ECC_SERRCOUNT_REG";
	case CVE_MMIO_HUB_ECC_DERRCOUNT_MMOFFSET:
		return "ECC_DERRCOUNT_REG";
	case CVE_MMIO_HUB_PARITY_ERRCOUNT_MMOFFSET:
		return "PARITY_ERRCOUNT_REG";
	case CVE_MMIO_HUB_UNMAPPED_ERR_ID_MMOFFSET:
		return "UNMAPPED_ERR_ID_REG";
	default:
		return get_other_regs_str(offset);
	}
}
