/********************************************
 * Copyright (C) 2019 Intel Corporation
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 ********************************************/

/**
 * @file sph_hwtrace_protocol.h
 *
 * @brief Header file defining sph hwtrace protocol
 *
 * This header file defines common types used in for card/host hwtrace protocol.
 *
 */


#ifndef _HWTRACE_PROTOCOL_H
#define _HWTRACE_PROTOCOL_H

enum SPH_HWTRACE_STATUS {
	SPHCS_HWTRACE_NOT_SUPPORTED = 0,
	SPHCS_HWTRACE_REGISTERED,
	SPHCS_HWTRACE_INITIALIZED,
	SPHCS_HWTRACE_ASIGNED,
	SPHCS_HWTRACE_ACTIVATED,
	SPHCS_HWTRACE_DEACTIVATED,
	SPHCS_HWTRACE_ERR
};

enum SPH_HWTRACE_ERROR {
	SPH_HWTRACE_NO_ERR = 0,
	SPH_HWTRACE_ERR_NOT_INITIALIZE = 99,
	SPH_HWTRACE_ERR_DTF_CHANNEL,
	SPH_HWTRACE_ERR_INTEL_TH_REG,
	SPH_HWTRACE_ERR_ADD_RESOURCE_FAIL,
	SPH_HWTRACE_ERR_UNLOCK_RESOURCE_FAIL,
	SPH_HWTRACE_ERR_RESOURCE_CLEANUP_FAIL,
	SPH_HWTRACE_ERR_NPK_TRACE_ALLOC_FAIL,
	SPH_HWTRACE_ERR_TRACE_RES_MAP_FAIL,
	SPH_HWTRACE_ERR_STREAM_RES_MAP_FAIL,
	SPH_HWTRACE_ERR_DMA_FAILED,
	SPH_HWTRACE_ERR_NO_MEMORY,
	SPH_HWTRACE_ERR_INVALID_OPCODE,
	SPH_HWTRACE_ERR_INVALID_VALUE,
	SPH_HWTRACE_ERR_INTERNAL_IO
};


enum SPH_HWTRACE_OPCODES {
	HWTRACE_INIT = 1,
	HWTRACE_DEINIT,
	HWTRACE_RESOURCE_CLEANUP,
	HWTRACE_QUERY_STATE,
	HWTRACE_UNLOCK_RESOURCE,
	HWTRACE_ADD_RESOURCE,
	HWTRACE_RESOURCE_READY,
	HWTRACE_LAST_RESOURCE_READY
};

#endif //_HWTRACE_PROTOCOL_H

