/********************************************
 * Copyright (C) 2019-2020 Intel Corporation
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 ********************************************/

/**
 * @file nnp_hwtrace_protocol.h
 *
 * @brief Header file defining sph hwtrace protocol
 *
 * This header file defines common types used in for card/host hwtrace protocol.
 *
 */


#ifndef _HWTRACE_PROTOCOL_H
#define _HWTRACE_PROTOCOL_H

enum NNP_HWTRACE_STATUS {
	NNPCS_HWTRACE_NOT_SUPPORTED = 0,
	NNPCS_HWTRACE_REGISTERED,
	NNPCS_HWTRACE_INITIALIZED,
	NNPCS_HWTRACE_ASIGNED,
	NNPCS_HWTRACE_ACTIVATED,
	NNPCS_HWTRACE_DEACTIVATED,
	NNPCS_HWTRACE_ERR
};

enum NNP_HWTRACE_ERROR {
	NNP_HWTRACE_ERR_NO_ERR = 0,
	NNP_HWTRACE_ERR_NOT_INITIALIZE = 99,
	NNP_HWTRACE_ERR_FAILED_DEINIT,
	NNP_HWTRACE_ERR_DTF_CHANNEL,
	NNP_HWTRACE_ERR_INTEL_TH_REG,
	NNP_HWTRACE_ERR_ADD_RESOURCE_FAIL,
	NNP_HWTRACE_ERR_UNLOCK_RESOURCE_FAIL,
	NNP_HWTRACE_ERR_RESOURCE_CLEANUP_FAIL,
	NNP_HWTRACE_ERR_NPK_TRACE_ALLOC_FAIL,
	NNP_HWTRACE_ERR_TRACE_RES_MAP_FAIL,
	NNP_HWTRACE_ERR_STREAM_RES_MAP_FAIL,
	NNP_HWTRACE_ERR_DMA_FAILED,
	NNP_HWTRACE_ERR_NO_MEMORY,
	NNP_HWTRACE_ERR_INVALID_OPCODE,
	NNP_HWTRACE_ERR_INVALID_VALUE,
	NNP_HWTRACE_ERR_INTERNAL_IO,
	NNP_HWTRACE_ERR_CARD_FATAL_ERROR
};


enum NNP_HWTRACE_OPCODES {
	HWTRACE_INIT = 1,
	HWTRACE_DEINIT,
	HWTRACE_RESOURCE_CLEANUP,
	HWTRACE_QUERY_STATE,
	HWTRACE_UNLOCK_RESOURCE,
	HWTRACE_ADD_RESOURCE,
	HWTRACE_RESOURCE_READY,
	HWTRACE_LAST_RESOURCE_READY,
	HWTRACE_GET_MEM_POOL_INFO
};

#endif //_HWTRACE_PROTOCOL_H

